netbirdio/dashboard

.github/workflows/build_and_push.yml
Adding ARM docker images
Closes #12
=> arm builds

src/components/addpeer/WindowsTab.js
The command that was written before does not seems to be working for me. I have updated it with the command that seems to work for me.
=> Update in command for Windows for v0.5

package-lock.json, package.json, src/views/Peers.js
implemented React-Table library
integrated a search function by name.
=> Implement Search & Filter #25

src/services/api-client/api-request.ts
=> As user to refresh page on 401

src/components/RouteUpdate.tsx, src/store/peer/types.ts, src/store/route/actions.ts, src/store/route/reducer.ts, src/store/route/sagas.ts, src/utils/routes.ts, src/views/Routes.tsx
Group routes and make updates that change all routes for the network group
=> Group network routes by identifier and range

src/components/PeerUpdate.tsx, src/components/SetupKeyNew.tsx, src/views/AccessControl.tsx, src/views/Peers.tsx, src/views/SetupKeys.tsx
Fixed all popover overlay when opening update modal
also fixed group input size problem with peers update
=> Fix popover for groups

package-lock.json, src/components/AccessControlNew.tsx, src/components/PeerUpdate.tsx, src/components/RouteUpdate.tsx, src/components/SetupKeyNew.tsx, src/services/api-client/header-factory.ts, src/utils/token.ts, src/views/AccessControl.tsx, src/views/Peers.tsx, src/views/Routes.tsx, src/views/SetupKeys.tsx, src/views/Users.tsx
The new hook exposes the getAccessTokenSilently function
that should be used to fetch access token.
The function returns a promise of a token and waits until
the OIDC lib renews the token if it expires.
=> Add access token hook to return valid token

src/components/SetupKeyNew.tsx, src/components/UserUpdate.tsx, src/store/setup-key/types.ts, src/store/user/actions.ts, src/store/user/reducer.ts, src/store/user/sagas.ts, src/store/user/service.ts, src/store/user/types.ts, src/views/SetupKeys.tsx, src/views/Users.tsx
Relates to https://github.com/netbirdio/netbird/issues/458 and https://github.com/netbirdio/netbird/pull/460
=> Peers auto-tagging with users and predefined groups

src/utils/token.ts
Using latestToken global allows to get the latest value in getAccessTokenSilently from useEffect updates
=> Parse access token for validation and use latestToke global

src/views/Peers.tsx, src/views/Users.tsx
when account has no peers
show button to redirect to add new peer page
add user grouping message when app.netbird.io
preview:
Add peer
Users message
=> Add new peer button and user message

docker/init_react_envs.sh, package-lock.json, package.json, src/App.tsx, src/config.json, src/config.ts
hotjar is only enabled if NETBIRD_HOTJAR_TRACK_ID is passed
=> Add hotjar integration

src/components/SetupKeyNew.tsx, src/store/setup-key/sagas.ts, src/store/setup-key/types.ts, src/utils/common.js, src/views/ExpiresInInput.tsx
=> Add setup key expiration property when creating new key

package-lock.json, package.json, src/components/Banner.tsx
We store the banner text as md5 and the state if user closed already
resolves #94
=> Don't display announcement after user close it

package-lock.json, package.json, src/index.tsx
follow up to #96
built version works as expected, no warnings or errors
=> bump @axa-fr/react-oidc to 6.9 to fix atob padding bug

src/components/UserUpdate.tsx
The name field should not be required, especially for self-hosted
Resolves https://github.com/netbirdio/netbird/issues/561
=> Check for change in any field

src/views/DNS.tsx, src/views/Peers.tsx
=> Filter peers by groups

src/components/NameServerGroupUpdate.tsx, src/store/nameservers/sagas.ts, src/views/DNS.tsx
Check if domains is not empty when primary is false
Validate domain and primary fields before submit
Display validation errors as message too
Reload groups on failure too
Display API call error
Added call to action message when nameserver is empty
=> Fix DNS validations

src/components/Navbar.tsx
Validate if the users state is empty and issue a GET call to /api/users
We check if the call was issued and if not on tabs that already does such a call
=> Call users API on empty state

README.md, src/components/Navbar.tsx, src/components/UserUpdate.tsx, src/store/user/types.ts
This feature allows using the custom claim in the JWT token as a user ID,
and this change linked to https://github.com/netbirdio/netbird/pull/667
https://github.com/netbirdio/netbird/issues/507
=> Feat add custom id claim

src/components/PeerUpdate.tsx, src/store/peer/types.ts, src/views/Peers.tsx
- Display if peer login has expired in the Peers table
- Enable/Disable peer login expiration
=> Add peer login expiration

src/utils/common.js
Capitalize the first letter of the OS
=> Capitalize first letter of OS

docker/init_react_envs.sh, src/components/addpeer/WindowsTab.tsx, src/config.json, src/config.ts
removed latestVersion logic and environment support
=> Use new windows release URL

src/components/UserUpdate.tsx, src/views/Users.tsx
prevent update for own user
use the is_current for label
removed unused imports
=> Use user.is_current

src/views/Activity.tsx
Related changes for https://github.com/netbirdio/netbird/pull/700
=> Add policy add activities

src/components/addpeer/AddPeerPopup.tsx, src/components/addpeer/MacTab.tsx, src/components/addpeer/UbuntuTab.tsx
=> Add single line installer command for Mac and Linux

src/components/SetupKeyNew.tsx, src/views/SetupKeys.tsx
Made focus on create setup key button when setup keys table is empty, remade modal for create and update setup key
=> Setup keys screen

src/components/UserEdit.tsx
=> Make breadcrumbs look like links

src/views/ServiceUsers.tsx
Removed unnecessary check from create button.
=> Enable creating service user for all domains

src/views/Activity.tsx
Related to https://github.com/netbirdio/netbird/pull/865
=> Track block/unblock user activity

src/components/UserEdit.tsx, src/views/RegularUsers.tsx
=> Make it more visible that user can be blocked

src/components/SetupKeyEdit.tsx, src/views/SetupKeys.tsx
=> Decrease length of the hidden setup key prefix

src/components/popups/addpeer/addpeer/DockerTab.tsx, src/components/popups/addpeer/addpeer/LinuxTab.tsx, src/components/popups/addpeer/addpeer/MacTab.tsx, src/components/popups/addpeer/addpeer/TabSteps.tsx, src/components/popups/addpeer/addpeer/UbuntuTab.tsx, src/components/popups/addpeer/addpeer/types.ts, src/index.css, src/views/AccessControl.tsx
add copy button on add peer code box and remove check to shoe default rule
=> add copy button on add peer code box and remove check to shoe default Rule

src/components/Navbar.tsx, src/utils/filterState.js, src/utils/pageSize.tsx, src/views/AccessControl.tsx, src/views/Activity.tsx, src/views/Nameservers.tsx, src/views/Peers.tsx, src/views/RegularUsers.tsx, src/views/Routes.tsx, src/views/ServiceUsers.tsx, src/views/SetupKeys.tsx
=> add all filter state on persist on page refresh

src/index.css, src/views/Settings.tsx
Replace tab view in the Settings panel with the left-handed
sidebar menu.
=> Sidebar menu for Settings

src/store/user/types.ts, src/utils/common.js, src/views/Activity.tsx, src/views/RegularUsers.tsx
Add last login to users overview list.
Additionally added new events for dashboard login, peer expiration and peer login.
=> Add User last login and new events

e2e-tests/pages/access-control-page.ts, e2e-tests/pages/login-page.ts, e2e-tests/pages/peers-page.ts, e2e-tests/tests/access-control.test.ts, e2e-tests/tests/peers.test.ts, playwright.config.ts, src/views/AccessControl.tsx
Fixed flaky test by changing the way to access Access Control Page and add some test ids of Add Rules buttons.
=> Fix flaky Access control test

src/components/SetupKeyEdit.tsx, src/views/SetupKeys.tsx
=> Add ephemeral peers views and subviews

src/views/SetupKeys.tsx
Fixing https://github.com/netbirdio/netbird/issues/1259
=> Removed disabled option from setup key filter switch

src/components/NameServerGroupAdd.tsx, src/utils/routes.ts
This fixes an issue with creating new custom NS group for an all resolver case
=> Init domains array for custom nameserver group

src/views/Settings.tsx
=> Add a settings page for custom IdP and MFA

src/modules/activity/ActivityDescription.tsx, src/modules/activity/ActivityTypeIcon.tsx
- Added posture check meta tags to the activity event description
- Added icon for posture checks
=> Add better description for posture check activity events

src/app/(dashboard)/peer/page.tsx, src/components/Card.tsx
=> Add option to copy peer details (ip, public ip, hostname, domain name)

src/modules/settings/AuthenticationTab.tsx, src/utils/helpers.ts
=> Add support for decimal expiration time and switch to days if interval exceeds 48h

src/modules/peers/PeersTable.tsx
=> Add 'Offline' filter to peers table

src/modules/routes/RouteModal.tsx
=> Fix typo in Routes

src/modules/settings/AuthenticationTab.tsx, src/modules/settings/GroupsTab.tsx, src/modules/settings/PermissionsTab.tsx
See issue: https://github.com/netbirdio/dashboard/issues/404
Thanks to  [taylorwilsdon](https://github.com/taylorwilsdon) for the detailed issue and fix
=> Fix settings PUT request overwriting values

src/modules/activity/ActivityDescription.tsx, src/modules/common-table-rows/EmptyRow.tsx, src/modules/setup-keys/SetupKeyActionCell.tsx, src/modules/setup-keys/SetupKeyGroupsCell.tsx, src/modules/setup-keys/SetupKeyKeyCell.tsx, src/modules/setup-keys/SetupKeyModal.tsx, src/modules/setup-keys/SetupKeyNameCell.tsx, src/modules/setup-keys/SetupKeyTypeCell.tsx, src/modules/setup-keys/SetupKeysTable.tsx
- Add support to key deletion
- Add custom and unlimited expiration
=> Add setup-key improvements

src/modules/networks/routing-peers/NetworkRoutingPeerModal.tsx
Related to this https://github.com/netbirdio/netbird/issues/3125
=> Fix wrong masquerade state for routing peer modal in networks
