netbirdio/dashboard

- src/components/AccessControlNew.tsx
- src/components/PeerGroupsUpdate.tsx
- src/views/Peers.tsx
Validate tag naming input
* check if only spaces has been added
* check if group All is being removed
* group All is not closeable in peers
Fixed issue when group list is too large, preventing click on the group counter
> Validate tag input and handle popover for 5+ groups

- package.json
- src/index.tsx
Service has caused some bugs where
the trust domains were ignored
and api calls were done without proper credentials
> Disable service worker

- src/components/PeerUpdate.tsx
- src/components/SetupKeyNew.tsx
- src/store/rule/sagas.ts
- src/store/setup-key/actions.ts
- src/store/setup-key/reducer.ts
- src/store/setup-key/sagas.ts
- src/store/setup-key/service.ts
- src/store/setup-key/types.ts
- src/utils/routes.ts
- src/views/AccessControl.tsx
- src/views/Peers.tsx
- src/views/SetupKeys.tsx
Relates to https://github.com/netbirdio/netbird/issues/458 and https://github.com/netbirdio/netbird/pull/460
> Support new PUT request for SetupKeys endpoint

- src/utils/token.ts
Related to https://github.com/netbirdio/netbird/issues/452
According to https://www.rfc-editor.org/rfc/rfc7515.txt, JWTs don't require padding in their base64 encoding, however JavaScript's `atob()` does require a padding. 
Update the `b64DecodeUnicode` function to re-add the padding if required.
> correctly handle JWTs without base64-padding

- package-lock.json
- package.json
- src/index.tsx
Reverts netbirdio/dashboard#97
@BeryJu unfortunately we will have to revert the PR as the new version's silent login has some issues that passed my tests, but they are more visible when working with shorter expiration times for your access tokens.
> Revert "bump @axa-fr/react-oidc to 6.9 to fix atob padding bug"

- src/components/addpeer/UbuntuTab.tsx
The use of apt-key has been deprecated for security reasons, and best practice is now to add keyrings to the directory `/etc/apt/trusted.gpg.d/`. 
When adding the gpg key using the current method, the following error is being displayed:
`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).`
Similar warning appears when running `apt update`:
`Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`
It should also be noted that apt-key(8) will last be available in Debian 11 and Ubuntu 22.04.
This PR edits one of the commands in the installation guide for Ubuntu-based distros, to use the new suggested method.
> fix: apt-key deprecation warning/errors

- src/components/PeerUpdate.tsx
- src/components/RouteUpdate.tsx
- src/store/route/actions.ts
- src/store/route/sagas.ts
- src/store/route/types.ts
- src/utils/routes.ts
- src/views/DNS.tsx
- src/views/Routes.tsx
Users can add distribution groups to network routes
Groups can be added to individual network routes or to all routes in the group
Adding a new group in the modal is restricted to individual network route operations
> Add distribution groups to Network routes

- src/components/addpeer/MacTab.tsx
- src/components/addpeer/UbuntuTab.tsx
- src/components/addpeer/common.ts
Currently, the `netbird up` command doesn't show the case, when running the netbird server components in the self-hosted mode in case of MacOS. This PR adds the support for it to show the `netbird up --management-url [self-hosted server]` for MacOS tab, similar to the ubuntu tab.
> Fix MacOS custom netbird up command  

- src/components/Navbar.tsx
- src/views/Users.tsx
With some IDPs like MS Azure the `oidcUser` is not being set, so we can fallback to id token to validate UI and current user
> Use ID token payload when oidcUser is nil

- src/App.tsx
- src/components/Navbar.tsx
- src/components/SetupKeyNew.tsx
- src/services/api-client/api-request.ts
- src/store/account/actions.ts
- src/store/account/index.ts
- src/store/account/reducer.ts
- src/store/account/sagas.ts
- src/store/account/service.ts
- src/store/account/types.ts
- src/store/index.ts
- src/store/root-action.ts
- src/store/root-reducer.ts
- src/views/DNSSettings.tsx
- src/views/ExpiresInInput.tsx
- src/views/Settings.tsx
New Settings tab added to the dashboard.
It is possible to enable or disable peer login expiration globally for an account.
As well as defining the expiration time period.
> Account settings view

- src/views/Settings.tsx
Add a confirmation dialog to notify a user of possible 
consequences of the peer login expiration enabling/disabling.
https://user-images.githubusercontent.com/700848/220278914-ba2b880e-f3fb-4fc3-afc0-f01db5cc2b44.mp4
> Add peer expiration setting confirmation modal

- src/views/Activity.tsx
Events peer.login.expiration.disable and peer.login.expiration.enable
are handled in the Activity tab now and properly displayed.
> Format individual peer login expiration event

- src/views/Activity.tsx
Handling of the "User role updated" event (user.role.update) was missing in the Activity tab.
> Display user in the user role update event

- src/components/AccessControlModalGroups.tsx
- src/utils/pageSize.tsx
- src/views/AccessControl.tsx
- src/views/Activity.tsx
- src/views/Nameservers.tsx
- src/views/Peers.tsx
- src/views/Routes.tsx
- src/views/SetupKeys.tsx
- src/views/Users.tsx
Reduce duplicated code with single helper for pagination
On larger deployments we should allow for larger pages
> Use single page size helper with new larger values

- src/index.css
> Make table headers font-weight normal

- src/components/RouteUpdate.tsx
- src/views/Routes.tsx
Fixed issues when updating routes that the existing routing peers get messed up.
Additionally fixed routing peer dropdown to filter already assigned routing peers.
> Fix Routes view when updating routes

- src/views/Routes.tsx
When clicking view in the dropdown menu of route peer update the name was showing wrong data and the groups where empty. FIxed that.
> Fix displaying groups on route peer update

- src/components/UserEdit.tsx
- src/store/user/sagas.ts
we had up to 11 requests on user edit due to reload. Reduced to the minimum possible
> Fix to many requestes on user edit

- src/views/AccessControl.tsx
- src/views/Nameservers.tsx
- src/views/Peers.tsx
- src/views/Routes.tsx
The lists where showing and empty button next to the ellipsis. Fixed it.
**Before:**
**After:**
> Fix empty button in lists

- src/components/UserEdit.tsx
When we click on any of the breadcrumbs the whole user page reloads which is anoying for the user because he has to wait for oauth to authenticate again.Fixed it to not reload page!
> Fix user view reload on breadcrumbs

- src/views/Peers.tsx
In safari the button in the main column was cutting of the other lines containing user email and expiration.
> Fix peers views in safari

- src/components/popups/addpeer/addpeer/AddPeerPopup.tsx
- src/components/popups/addpeer/addpeer/MacTab.tsx
- src/index.css
Updating the popup for adding a peer on MacOS to recommend pkg installer primarily and move commandline istall as secondary.
Before: 
After:
> Add pkg installer to MacOS Popup

- src/components/popups/AddPATPopup.tsx
We were showing a false error message "PAT creation failed" if you enter a group and confirm by pressing enter.
> Fix false error message on group enter

- src/components/UserEdit.tsx
- src/views/Peers.tsx
A user reported an issue with the UI that the autogroups filed on the user view was disabled even tho he is admin. The autogroups box used old isAdmin check depending on oidc (which should still work fine on fully configured IdP, but this way we will be more resillient). Replace this and on peers view to not depend on oidc.
> Fix isAdmin check to not depend on oidc

- .gitignore
For multiple IdPs I have a config each to simply switch for testing that should not be uploaded by accident.
> Extend gitignore to ignore multiple config files

- src/components/SetupKeyNew.tsx
- src/views/SetupKeys.tsx
The setup keys popup was not setting the default expiration properly.
> Fix default value for expiration for setup keys

- docker/init_react_envs.sh
by setting the AUTH_AUDIENCE=none we will unset the audience value, not passing that to the requests
This is required for the jumpcloud support
> Allow unset audience

- src/App.tsx
- src/index.tsx
- src/views/Install.tsx
This page allows to display installation steps without 
authentication. Can be referenced from the landing
page. for example.
> Add public installation page

- .github/workflows/build_and_push.yml
- .github/workflows/e2e-tests.yml
- .gitignore
- e2e-tests/clean-test-env.sh
- e2e-tests/create-test-env.sh
- e2e-tests/pages/modals/add-peer-modal.ts
- e2e-tests/pages/peers-page.ts
- e2e-tests/pages/top-menu.ts
- e2e-tests/test-env.sh
- e2e-tests/tests/access-control.test.ts
- e2e-tests/tests/peers.test.ts
- package-lock.json
- package.json
- playwright.config.ts
- src/components/Navbar.tsx
- src/components/popups/addpeer/addpeer/AddPeerPopup.tsx
- src/components/popups/addpeer/addpeer/AndroidTab.tsx
- src/components/popups/addpeer/addpeer/DockerTab.tsx
- src/components/popups/addpeer/addpeer/MacTab.tsx
- src/components/popups/addpeer/addpeer/WindowsTab.tsx
- src/views/AccessControl.tsx
- src/views/Peers.tsx
Add tests with playwright for:
- add peer modal on first access
- add peer modal on empty peer list
- test install buttons and instructions for Linux, Docker, macOS, Windows and Android
- check default ACL
The tests are using a modified version of the getting started scripts to run a local environment of management services and run the dashboard from the current version
Todo: 
- run tests before create docker container
- add more tests
> Add end-to-end tests using playwright

- src/components/popups/addpeer/addpeer/AndroidTab.tsx
- src/components/popups/addpeer/addpeer/MacTab.tsx
- src/components/popups/addpeer/addpeer/WindowsTab.tsx
Implemented #93
Edit: Added android too
> Add windows/macos/android instructions for self-hosted

- src/components/Navbar.tsx
- src/components/UserEdit.tsx
- src/index.css
- src/store/peer/sagas.ts
- src/views/Peers.tsx
1. Show only the peers tab
2. Show only peers that belong to the current logged in user (by email)
3. Hide SSH Server and Groups columns
4. Disable peers detailed view (just don't allow it)
> Limit UI view for the "user" role

- src/components/PeerUpdate.tsx
Linux machine view (with Network Routes section)
Non-Linux machine view (without Network Routes section)
> Hide network routes card for non-linux peers

- src/views/RegularUsers.tsx
In the users overview we added the last login information. This is only shown for entries that have a tag (me, blocked, invited). This PR also adds it for regular entries without tag
> Fix last login for regular entries in users overview

- src/views/Settings.tsx
The settings page was not shown on self-hosted but on prod. This needed to be inverted.
> Fix JWT group sync settings visibility

- src/components/PeerUpdate.tsx
- src/components/RouteAddNew.tsx
- src/components/RoutePeerUpdate.tsx
- src/components/RouteUpdate.tsx
- src/components/SetupKeyEdit.tsx
- src/index.css
- src/store/route/sagas.ts
- src/store/route/types.ts
- src/utils/routes.ts
- src/views/Peers.tsx
- src/views/Routes.tsx
- src/views/SetupKeys.tsx
User can add routing peer or group peer from add route peer popup
Also user can edit routing peer same as before and group routing
on edit user cant switch tab
user can configure grouping routing and when that way can can quick edit from there
availablilty badge will be turn on if selected grouping has more then one unique peer
> add, delete, edit and configure peer gropus

- src/components/Navbar.tsx
- src/components/UserEdit.tsx
- src/views/Activity.tsx
- src/views/Peers.tsx
- src/views/RegularUsers.tsx
- src/views/Users.tsx
Update checks for admin to include owner role
Updated role list to include role for users
Updated activity with new event type handler
Links to: https://github.com/netbirdio/netbird/pull/1340
> Add owner role support

- src/store/account/actions.ts
- src/store/account/reducer.ts
- src/store/account/sagas.ts
- src/store/account/service.ts
- src/views/Settings.tsx
Add support for deleting an account via dashboard in a settings `Danger zone` menu. The setting menu is available only to owner users.
After an account is deleted, a popup with a redirect message is displayed, and the user is logged out and redirected to the login page.
Flow screenshots:
Danger zone:
Deleting confirmation:
After deleting the notification:
> Add delete account support

- .github/workflows/codespell.yml
- docker/README.md
- e2e-tests/create-test-env.sh
- e2e-tests/pages/access-control-page.ts
Note: I spotted also typo in the some functions name in e2e-tests/pages/access-control-page.ts, if someone want change them in future PR. In this PR I don't change functions name.
> add codespell github workflow and fix some typo

- src/views/Settings.tsx
The API call to save settings was sending extra settings for selfhosted setups.
> Fix sending extra settings on selfhosted deployments

- src/views/Peers.tsx
User Approve for the approve peer modal. e.g.:
> Use Approve for approve peer modal

- src/utils/api.tsx
Add additional check if token is expired to prevent the browser from firing an api call before token has been refreshed.
> Add additional check if token is expired 

- src/app/(dashboard)/peer/page.tsx
- src/modules/access-control/AccessControlModal.tsx
- src/modules/access-control/table/AccessControlTable.tsx
- src/modules/groups/useGroupHelper.tsx
- src/modules/routes/RouteModal.tsx
- src/modules/routes/RouteUpdateModal.tsx
- Fix an issue where creating new groups in the access control modal would create a duplicate if the group does not exist and was used in the "source" and "destination" field
- Add additional check to prevent adding "null" to peer_groups
> Fix duplicate groups issue when group does not exist

- src/app/(dashboard)/peers/page.tsx
- src/app/(dashboard)/team/user/page.tsx
- src/app/globals.css
- src/components/Breadcrumbs.tsx
- src/components/PeerGroupSelector.tsx
- src/components/Steps.tsx
- src/contexts/CountryProvider.tsx
- src/contexts/GroupsProvider.tsx
- src/layouts/DashboardLayout.tsx
- src/layouts/Header.tsx
- src/modules/setup-netbird-modal/SetupModal.tsx
> Reduce information visible to regular users (non-adminstrators)

- src/app/(dashboard)/peers/page.tsx
- src/contexts/GroupsProvider.tsx
Sometimes, updating a group for a user with `group propagation` enabled doesn’t trigger a refresh in the peer view. 
This PR includes a fix to trigger a refresh of the groups once the peer's table is visited again.
> Fix peer groups occasionally not refreshing 

- src/components/table/DataTable.tsx
- src/components/table/DataTableResetFilterButton.tsx
Changes
- A button to reset the filter, search & pagination state was added to all tables. The button will only be visible if there is either a search value entered or if there are any filters set.
Default (Without any filters) 
Filters set (button visible)
> Add reset button to tables

- src/app/(dashboard)/peer/page.tsx
- src/app/(dashboard)/peers/page.tsx
- src/contexts/CountryProvider.tsx
- src/contexts/GroupsProvider.tsx
- src/layouts/DashboardLayout.tsx
- src/modules/common-table-rows/GroupsRow.tsx
- src/modules/peers/PeersTable.tsx
This PR reverts the recent changes in the peer's view. 
Regular users can now view their peers.
Some actions that regular users can not perform are hidden (delete peer, enable ssh, etc.)
Fields that require admin permissions are now disabled for regular users.
> Show peers for regular users but hide / disable actions (delete, enable ssh etc.)

- src/modules/users/table-cells/UserActionCell.tsx
The user deletion notification didn't have a space/match the style of the other deletion stages before (title would be e.g. Userdeleted).
This updates the notification to match the style of the rest of the deletion stages (encasing the name in ') as well as adding the missing space between the name and deleted.
> Fix user deletion notification

- src/app/(dashboard)/setup-keys/page.tsx
- src/components/table/DataTable.tsx
- src/components/ui/GroupBadge.tsx
- src/modules/groups/GroupSelector.tsx
- src/modules/peers/PeersTable.tsx
- src/modules/setup-keys/SetupKeyActionCell.tsx
- src/modules/setup-keys/SetupKeyGroupsCell.tsx
- src/modules/setup-keys/SetupKeysTable.tsx
- src/modules/setup-keys/SetupKeysTableColumns.tsx
Changes:
- Do not return `undefined` if the setup keys `auto_groups` has a group that does not exist
- Add a try catch block for the global search 
- Do not load setup keys modal if it's not open
> Add fallbacks for setup key name & setup key group names

- src/components/Notification.tsx
- src/contexts/RoutesProvider.tsx
- src/modules/dns-nameservers/NameserverModal.tsx
- src/modules/routes/RouteModal.tsx
- src/modules/routes/RouteUpdateModal.tsx
- src/modules/setup-keys/SetupKeyModal.tsx
- src/utils/api.tsx
> Add better input validation for setup-keys, nameserver and routes

- src/utils/helpers.ts
This PR fixes the isValidDomain regex to allow single char domain names like `a.bc.com`
Tested the regex with the following set:
```
console.log(isValidDomain("p.abc.com")); // true
console.log(isValidDomain("example.com")); // true
console.log(isValidDomain("invalid domain")); // false
console.log(isValidDomain("a..b")); // false
console.log(isValidDomain(".3.v")); // false
console.log(isValidDomain("a-b.com")); // true
console.log(isValidDomain("a.b")); // true
console.log(isValidDomain("ab.bc.de")); // true
console.log(isValidDomain("a-b.dc.de")); // true
console.log(isValidDomain("a--b.com")); // false
console.log(isValidDomain("-abc.com")); // false
console.log(isValidDomain("abc-.com")); // false
console.log(isValidDomain("abc..com")); // false
```
> Fix DNS modal to allow one char domains

- src/utils/netbird.ts
This change adds a flag to the `netbird up` command when the site is not hosted by netbird.io or wiretrustee.com
> Add admin-url to the add-peer dialogue

- src/app/(dashboard)/peer/page.tsx
- src/interfaces/Peer.ts
- src/modules/groups/AssignPeerToGroupModal.tsx
- src/modules/peers/PeerOSCell.tsx
- src/modules/peers/PeersTable.tsx
* add serial on peers list (included in OS information to minimize informations)
* permit a lookup via serial number
* add serial on peer information
> display serial number on peer information and on peers table

- src/modules/peers/PeerNameCell.tsx
https://github.com/netbirdio/dashboard/issues/449
https://github.com/netbirdio/netbird/issues/3537
Before
After
> Add display of ID if user does not have email

- src/modules/posture-checks/table/PostureCheckBrowseTable.tsx
Fix the issue where browsing posture checks would use filters / search from the access control policies table.
See issue: https://github.com/netbirdio/netbird/issues/3377
> Fix posture checks table filters
